[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"

[functions]
  included_files = ["prisma/schema.prisma"]

[functions."cleanup-videos"]
  schedule = "@daily"

[[plugins]]
  package = "@netlify/plugin-nextjs"
